"""empty message

Revision ID: c4cd854034ca
Revises: 67846672397d
Create Date: 2024-06-03 00:45:26.056142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cd854034ca'
down_revision: Union[str, None] = '67846672397d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('cloud_vm_name', sa.String(length=100), nullable=False))
    op.drop_constraint('servers_cloud_vm_id_key', 'servers', type_='unique')
    op.create_unique_constraint(None, 'servers', ['cloud_vm_name'])
    op.drop_column('servers', 'cloud_vm_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('cloud_vm_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'servers', type_='unique')
    op.create_unique_constraint('servers_cloud_vm_id_key', 'servers', ['cloud_vm_id'])
    op.drop_column('servers', 'cloud_vm_name')
    # ### end Alembic commands ###
