"""initial2

Revision ID: a106e16c8b50
Revises: fc21b79fa81b
Create Date: 2024-05-24 01:05:37.271168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a106e16c8b50'
down_revision: Union[str, None] = 'fc21b79fa81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_sys_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_sys_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
